#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/users/missirol/test/dev/CMSSW_12_3_0/CMSHLT_2288/IntegTest_v01/HLT"           # no version, take the latest one
TARGET="/users/missirol/test/dev/CMSSW_12_3_0/CMSHLT_2288/IntegTest_v01/TABLE"         # directory where to store the sub-tables
TABLES="GRun HIon PIon PRef"             # which sub-tables to create

source subtables.sh
createSubtables "v3/run3" "$MASTER" "$TARGET" "$TABLES"
