#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/users/missirol/test/taskify/test01/HLT"           # no version, take the latest one
TARGET="/users/missirol/test/taskify/test01/TABLE"         # directory where to store the sub-tables
TABLES="GRun HIon PIon PRef"             # which sub-tables to create

source subtables.sh
createSubtables "v3-test/dev" "$MASTER" "$TARGET" "$TABLES"
