#! /bin/bash
#
# generate HLT tables from master table in ConfDB
#

MASTER="/dev/CMSSW_12_4_0/HLT"                      # no version, take the latest one
TARGET="/users/missirol/test/dev/CMSSW_12_4_0/CMSHLT_2515/Test01/HLT"      # where to store the online-compliant menu
TABLES="online_hion"

source subtables.sh
createSubtables "v3/run3" "$MASTER" "$TARGET" "$TABLES"
