#ifndef HeterogeneousCore_AlpakaCore_interface_JobConfigurationAlpakaRecord_h
#define HeterogeneousCore_AlpakaCore_interface_JobConfigurationAlpakaRecord_h

#include "FWCore/Framework/interface/EventSetupRecordImplementation.h"

class JobConfigurationAlpakaRecord : public edm::eventsetup::EventSetupRecordImplementation<JobConfigurationAlpakaRecord> {};

#endif  // HeterogeneousCore_AlpakaCore_interface_JobConfigurationAlpakaRecord_h
